# Generated by Django 5.1.3 on 2024-12-28 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_poll_choice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="voted_users",
            field=models.ManyToManyField(
                blank=True, related_name="voted_polls", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
